# Generated by Django 5.0.6 on 2024-08-26 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_userprofile_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
